# Generated by Django 3.1.5 on 2022-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0004_menu_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='排序'),
        ),
    ]
