# Generated by Django 3.2.14 on 2022-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ddjh_px',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('sb_moduleid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sb_modulepair', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('wx_moduleid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('wx_modulepair', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rec_moduleid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rec_modulepair', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nm_moduleid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nm_modulepair', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fy_moduleid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fy_modulepair', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('beizhu', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('setup_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '调度交换配线',
                'verbose_name_plural': '调度交换配线',
                'db_table': 'Ddjh_px',
                'managed': True,
            },
        ),
    ]
