# Generated by Django 3.2.14 on 2022-07-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('loginid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='登录账号')),
                ('loginpwd', models.CharField(max_length=200, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
                ('department', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='职位')),
                ('mobile', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='邮箱地址')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='上次登录时间')),
                ('create_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
                'db_table': 'user_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('icon', models.CharField(default=None, max_length=100, null=True, verbose_name='图标')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'user_Menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='角色描述')),
                ('account', models.ManyToManyField(to='userweb.Account', verbose_name='账号')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'usr_Roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='url')),
                ('order', models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='排序')),
                ('menu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='userweb.menu', verbose_name='菜单')),
                ('roles', models.ManyToManyField(default=None, null=True, to='userweb.Roles', verbose_name='角色')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'user_Permission',
                'managed': True,
            },
        ),
    ]
