# Generated by Django 3.2.12 on 2022-07-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='类型名称')),
                ('name', models.CharField(max_length=50, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备分类',
                'verbose_name_plural': '设备分类',
                'db_table': 'shebei_classify',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(default='默认值', max_length=50, verbose_name='站点等级')),
            ],
            options={
                'verbose_name': '站点等级',
                'verbose_name_plural': '站点等级',
                'db_table': 'station_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认值', max_length=50, verbose_name='管理模式')),
            ],
            options={
                'verbose_name': '管理模式',
                'verbose_name_plural': '管理模式',
                'db_table': 'station_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='默认值', max_length=50, verbose_name='所在区域')),
            ],
            options={
                'verbose_name': '所在区域',
                'verbose_name_plural': '所在区域',
                'db_table': 'station_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='站点名称')),
                ('build_date', models.DateField(null=True, verbose_name='投运日期')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseweb.level')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseweb.model')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseweb.region')),
            ],
            options={
                'verbose_name': '通信站点',
                'verbose_name_plural': '通信站点',
                'db_table': 'tele_station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='stationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='图片名称')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='图片标注')),
                ('des', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片描述')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
                ('shebei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseweb.classify')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseweb.station')),
            ],
            options={
                'verbose_name': '通信图片',
                'verbose_name_plural': '通信图片',
                'db_table': 'tele_image',
                'managed': True,
            },
        ),
    ]
