# Generated by Django 3.2.12 on 2022-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level_name',
            new_name='name',
        ),
    ]
