# Generated by Django 3.2.12 on 2022-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseweb', '0002_rename_level_name_level_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
    ]
