# Generated by Django 3.2.14 on 2022-07-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shebei_class',
            fields=[
                ('classid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='类型名称')),
                ('classname', models.CharField(max_length=50, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备分类',
                'verbose_name_plural': '设备分类',
                'db_table': 'shebei_class',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='站点名称'),
        ),
        migrations.CreateModel(
            name='stationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='图片名称')),
                ('image_remark', models.CharField(max_length=1000, verbose_name='图片标注')),
                ('image_des', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片描述')),
                ('creat_date', models.DateField(verbose_name='创建时间')),
                ('image_shebei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.shebei_class')),
                ('image_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.station')),
            ],
            options={
                'verbose_name': '设备图片',
                'verbose_name_plural': '设备图片',
                'db_table': 'stationimage',
                'managed': True,
            },
        ),
    ]
