# Generated by Django 3.2.14 on 2022-07-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0002_auto_20220727_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationimage',
            name='image_remark',
            field=models.CharField(max_length=1000, null=True, verbose_name='图片标注'),
        ),
    ]
