# Generated by Django 3.2.14 on 2022-07-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(default='默认值', max_length=50, verbose_name='站点等级')),
            ],
            options={
                'verbose_name': '站点等级',
                'verbose_name_plural': '站点等级',
                'db_table': 'station_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='默认值', max_length=50, verbose_name='所在区域')),
            ],
            options={
                'verbose_name': '所在区域',
                'verbose_name_plural': '所在区域',
                'db_table': 'station_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='stationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='默认值', max_length=50, verbose_name='管理模式')),
            ],
            options={
                'verbose_name': '管理模式',
                'verbose_name_plural': '管理模式',
                'db_table': 'station_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(default='默认值', max_length=50, primary_key=True, serialize=False, verbose_name='站点名称')),
                ('build_date', models.DateField(null=True, verbose_name='投运日期')),
                ('station_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.level')),
                ('station_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.stationmodel')),
                ('station_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basement.region')),
            ],
            options={
                'verbose_name': '通信站点',
                'verbose_name_plural': '通信站点',
                'db_table': 'tele_station',
                'managed': True,
            },
        ),
    ]
