# Generated by Django 3.2.14 on 2022-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basement', '0003_alter_stationimage_image_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationimage',
            name='creat_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='image_remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='图片标注'),
        ),
    ]
